version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    links:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: client
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - REACT_APP_SERVER_URL=http://server:5000

volumes:
  mongodb_data:
